### ISSUE TITLE
大部分插件源码和V2RaySocks相似度极高

### ISSUE THREAD

**Issue by Zzm317** [Npist/v2rayMS#1]
很大部分插件源码和V2RaySocks相似度极高
演示站涉及抄袭
请做出解释

**Comment by Npist** [comment]
数据更新源码主要框架为Python的socketserver模块
仅实现简单的数据socket传递 没有任何复杂逻辑
演示站只有一个节点用来演示程序  相较本处内容也只仅仅加强了socket传输中的安全性
使用whmcs模版为Neworld开源模版https://github.com/tension/NeWorld-For-WHMCS
whmcs模块修改自SSR模块https://github.com/kesuki/whmcs-shadowsocks-plugin的早期版本（因为本机上的代码很久没有更新过） README.md已说明  如果是这块有问题我可以删除关于前端的部分  原本我这个程序只是服务器给各节点的用户数据分发的实现

**Comment by Zzm317** [comment]
@seqilove 按照您的说法 我维护UnlimitedSocks那么久也是为了赚钱？您又怎么知道作者有没有私下提供收费的服务？况且我不认为直接自己开一个项目并且混在一起是一个适合维护的想法。并且我还要提醒你一点 V2raySocks插件是开源的 也就是说你完全可以按照插件自己开发后端。如果你没有这个能力，你可以出钱购买我适配的后端，而不是说V2raySocks必须使用我的后端才能工作这一点你必须搞清楚。
目前这个项目本身就存在诸多问题，根据作者的回复和我目前了解到的情况，我并没有说有特别的反对。相反我建议作者使用V2raySocks来进行开发，因为他的这个去除了太多原有的功能，我不太赞同他的劣化做法。
你一个什么都不清楚的user来这边下面喷什么？

**Comment by Zzm317** [comment]
@seqilove 作为一个不会技术的用户，请不要尝试去干涉开发者的领域。包括为什么我这几天都没有回，因为我在进行严格的代码检查，来判断是不是有这个必要去删除或怎么样。你一个什么都不懂的用户跑过来张口就喷我收费有意思？python和go哪个更适合原生v2ray的数据获取以及资源上报这个我觉得不需要做讨论吧？修改json再启动的方式和使用grpc传输的方式的优劣不需要讨论吧？如果我想做完全收费，我要做的很简单，在插件里面留点bug加点后门，就那么简单。然而事实上呢？V2raySocks一直在进行bug的修复和功能的更新。如果你觉得这个项目曾经涉嫌付费，那请去看看某人的ls魔改V2ray插件再来评价谢谢。V2raySocks做到了尽可能将所有的功能打包出常用sdk以便用户自行开发，尤其是客户端，我提供了好几种现成的sdk，开发者需要做的只是简单的适配。在这种情况下，您是站在哪个道德的高地上来喷我的呢？MyInfinity用户那么广也不见得有多少人给我捐赠，那为什么我在已知这种结果的情况下还要将这样一个花费了我go语言学习时间成本的项目开源出来呢？

**Comment by Zzm317** [comment]
@seqilove 并且演示站涉及描述抄袭，这个是后端售后群的人反馈的情况，直接复制的。在这种情况下，保障用户的利益前来询问难道是为了宣传我的后端？简直不可理喻。

**Comment by seqilove** [comment]
我只是做出了我个人的判断并且指出了一个事实，不知道你哪里看出来我喷你？并且直接就对我进行人身攻击“一个不会技术的用户” “什么都不懂的用户”，其实大可不必恼羞成怒的，也不必欲盖弥彰。
既然你“包括为什么我这几天都没有回，因为我在进行严格的代码检查”，那么你为什么在检查之前就跑过来指责作者抄袭？“并且演示站涉及描述抄袭，这个是后端售后群的人反馈的情况，直接复制的。”，因为你的客户说涉及抄袭，然后你就没检查代码就直接认定了？到底谁不可理喻？
http://www.mak-blog.com/whmcs-shadowsocks-plugin.html这个插件如果是你开发的，请解释下为什么和神奇海螺的whmcs-shadowsocks-plugin这个收费插件的代码那么雷同？我们也不需要在这个issues里辩论什么了，直接去hostloc 开个贴，毕竟whmcs-shadowsocks-plugin的原作者就是论坛里面的。
我说明下为什么支持这个作者：1.他明确的在ReadME.Md里说明了他借鉴的来源，并且遵守了来源项目所遵守的GPL v3.0协议.
2.抄袭和借鉴的区别，如果说作者为了名或利，直接盗用别人的代码项目，那么当然是可耻。但是本项目不存在这种情况，作者更新的项目内容，在你看来可能是劣化，不成熟。却恰恰表明作者没有抄袭。我们对这些加入开源的新人，是不是不要那么苛刻？

写在最后，本来我没必要和人在网上争个长短，事情的起因很简单：我Fork了我感兴趣的一个项目，在花了半小时查看了项目代码后，习惯性的点开了Issues，然后发现了@Zzm317指责的话语，并且看了作者的回复后，我查看了相关的项目代码，顺带还翻出了15年就在我硬盘里的神奇海螺的whmcs-shadowsocks-plugin插件源码.虽然我不是什么大牛，但是作为一个06年就接触php的中年码农，简单的代码逻辑还是看得懂的.我对我做出的自认为公正的发言负责.
至于开源作者提供收费服务这件事，其实我是赞成的。好了，就这样吧。

**Comment by Zzm317** [comment]
@seqilove 你觉得我哪里进行指责了？如果你想去通过证明whmcs-shadowsocks-plugin有代码层的质量问题和版权问题，简单。先把你fork的某ls魔改项目删掉然后让作者删掉再来说话。您fork的那位作者可比您高级多了，一开始也是直接修改的US，被我发现后才转向使用了LS。如果你觉得“请做出解释“这种话是指责的话，我无话可说，这涉及到你语文不太好的问题。您那么喜欢mjj论坛那您就去呗，找个真大神写个插件再写个后端，别来这项目下面污染issue啊，本身就是非常技术性的issue。原作者的反馈非常有理有据且详细完整，不知道您哪里来的勇气一上来就站在道德高地上开喷。
我不清楚whmcs-shadowsocks-plugin的真正前世今生，我只知道我接手后改了一堆东西，然后这个项目我看的时候确实是直接修改的whmcs-shadowsocks-plugin。这个没得洗，您眼睛那么好能直接找到说“啊这个人fork的是我接手之前的分支，超厉害的“这样？那您可真是睿智的大神了。聊不来聊不来，您那么厉害，06年的老码农，可还是移步自己的项目自己写个插件吧，我等垃圾开发者伺候不起您这种用户。

**Comment by Zzm317** [comment]
“2.抄袭和借鉴的区别，如果说作者为了名或利，直接盗用别人的代码项目，那么当然是可耻。但是本项目不存在这种情况，作者更新的项目内容，在你看来可能是劣化，不成熟。却恰恰表明作者没有抄袭。我们对这些加入开源的新人，是不是不要那么苛刻？”
这个洗地简直666。本项目作者看到你这样说他大概得气的吐出三升血。开源项目不是为了名气你是在逗我？作者目前确实没有实现一些功能，函数命名也完全不符合WHMCS规范，这不是劣化这还是优化？这洗地真的，太伤人了吧？
至于“1.他明确的在ReadME.Md里说明了他借鉴的来源，并且遵守了来源项目所遵守的GPL v3.0协议.”，借鉴可还行，人家自己都说了“whmcs模块修改自SSR模块https://github.com/kesuki/whmcs-shadowsocks-plugin 的早期版本（因为本机上的代码很久没有更新过） README.md已说明”，你这样反而把他贬低了。毕竟借鉴到代码都一样那可真牛逼，你这黑的作者得气出一头白发。作者内心OS：我好好地“修改自”怎么就变成“借鉴”了啊我的妈这锅我不背。
啊顺便，您可长点心吧，有人把您黑历史都刨出来了，看了我也是一脸懵逼，感叹您内心的强大和乌漆麻黑，怪不得k总都退了mjj论坛，还真是有那么点道理的hhhhhh
close了，你爱撕或者怎么样就继续撕，反正大不了搞个多台直播娱乐一下大众也好，让大家看看这是单方面吊撕还是什么

**Comment by seqilove** [comment]
至于我的黑历史，我都不知道呢，如果有请说出来，不要一副我知道你干过什么坏事的模样。网络发言自由，但并不是精神病患者臆想狂随意捏造虚构的事实的地方！
问题的关键可能是你的自大和脆弱的自尊心不允许你收到别人的反驳而已，你自己看下你写的这些，满满的自我幻想和对他人恶意的攻击。。。真心疼你的教育环境和家庭环境。

**Comment by Zzm317** [comment]
谎话张嘴就来可还行，至于“你一直回避自己抄袭的事实”可还行，我哪里抄袭了请明确指出不然就是诽谤。UnlimitedSocks甚至都只是一个fork的项目，你有问题找始作者 @kesuki 去，别来往我身上泼脏水。如果你觉得我“自大和脆弱的自尊心不允许你收到别人的反驳”，那简单，首先，你既然觉得始作者抄袭，那都别用这个插件了，如果始项目就涉及抄袭，那后面的所有项目都涉及抄袭，都得删，没得逼逼，你又想说我抄袭又想说本项目作者没抄袭也真是双标的可以。至于“满满的自我幻想和对他人恶意的攻击。。。真心疼你的教育环境和家庭环境。”，可还行，我攻击你什么了？你难道不是一个普通的什么都不懂的用户？你难道还是一个参与了开发的熟悉插件业务逻辑的开发者？给自己洗地把你洗地的本项目也拖下水真的牛逼

**Comment by Zzm317** [comment]
“明明为了赚钱 非要一幅开源先驱的嘴脸？”可还行，我完全有重写插件的实力，至于为什么开源，你自己用你那不灵光的脑瓜想想清楚。这插件我完全可以做套授权，就好像LS一样，而我选择开源，为其他后端的开发提供了便利。你在享受到这份便利的同时还不忘踩我也是真的可以说非常不要脸了

**Comment by Zzm317** [comment]
还是这段话 “你一直回避自己抄袭的事实” 如果你觉得始作者的项目 whmcs-shadowsocks-plugin 涉嫌抄袭，简单，去 whmcs-shadowsocks-plugin 开个issue让他删掉项目，在这个项目也下面开个项目让他删掉项目或者插件，不就好了。你又想黑我又想维护本项目开发者的嘴脸真的恶心。我只是 whmcs-shadowsocks-plugin 的接手者不是原作者，所以如果你觉得 whmcs-shadowsocks-plugin 抄袭，那么本项目的whmcs插件是修改自 whmcs-shadowsocks-plugin 的，那也逃不开你所说的抄袭。你给作者开个issue，别继续bb，让他删项目就好，就那么简单的事情

**Comment by Zzm317** [comment]
啊对了 如果你觉得 whmcs-shadowsocks-plugin 是抄袭的话，你所说的”借鉴“，也就是抄袭没得洗了。本项目插件本身就是 “我的初始版本来自http://www.mak-blog.com/whmcs-shadowsocks-plugin.html
大概在2017年5月份左右在https://github.com/kesuki/whmcs-shadowsocks-plugin git clone到的” 也就是说是 whmcs-shadowsocks-plugin 的分支衍生项目，不存在任何意义的“借鉴”，就是单纯的“whmcs模块修改自SSR模块https://github.com/kesuki/whmcs-shadowsocks-plugin 的早期版本” 也就是你所说的，修改了涉及抄袭的源码，也就是说，你一边说他没抄袭一边又说他抄袭，可真的还行。这不是双标还是什么？

**Comment by Zzm317** [comment]
@seqilove 总之，如果你对 whmcs-shadowsocks-plugin 有什么不满，去 https://github.com/kesuki/whmcs-shadowsocks-plugin 开个issue，说明完整的涉及抄袭的逻辑，并且联系上 @kesuki 让他删项目就好，然后别忘了在本项目下面也开个issue让 @Npist 删掉这个项目的whmcs插件，因为是修改自 https://github.com/kesuki/whmcs-shadowsocks-plugin 的版本，所以也得删。然后既然你那么正义了，那你也可以顺便再去你fork的某个LS修改项目下面也提个issue，让他删项目，因为那个是直接修改的LegendSocks。

**Comment by Zzm317** [comment]
@seqilove 别忘了在本项目提issue的时候也要说个“涉及抄袭”偶～ 毕竟在你眼里接盘侠才是抄袭者，那 @Npist 也算个接盘的，也摆脱不了抄袭的帽子～ 毕竟 @Npist 和 本人 都是 whmcs-shadowsocks-plugin 的二开作者～

**Comment by seqilove** [comment]
你的二开真的很特别呢！项目说明里面完全没有提到你抄袭的对象呢，至少这个作者遵守GPL V3.0协议，把他借鉴参考的对象详细的说明了。你呢？呵呵。。。真的优秀啊

**Comment by seqilove** [comment]
你站在别人的肩膀上收获了成果，却不允许其他人站在你的肩膀上。这就是问题所在

**Comment by Zzm317** [comment]
@seqilove 我只是接盘的，我不对插件原项目进行任何来源性检查，我只对后面的分支项目负责。
这套逻辑很简单 如果你觉得 whmcs-shadowsocks-plugin 涉及抄袭，那么二次开发的我和 @Npist 都是涉及抄袭，因为 whmcs-shadowsocks-plugin 都涉及所谓的抄袭的话，那么两个二开项目里面的代码均有 whmcs-shadowsocks-plugin 的代码存在。就那么简单。顺便，如果你还想继续说借鉴打自己脸请继续。本项目作者说的清清楚楚 “whmcs模块修改自SSR模块https://github.com/kesuki/whmcs-shadowsocks-plugin 的早期版本” ，修改和借鉴是两种东西没得洗。再顺便GPLV3是什么你看看清楚再来谈。
您的逻辑太过优秀以至于您自己都没看出来至始至终您都在打自己脸，真可笑

**Comment by Zzm317** [comment]
@seqilove “你站在别人的肩膀上收获了成果，却不允许其他人站在你的肩膀上。这就是问题所在” 我不允许别人站在我的肩膀上？搞笑，去看看我提的第二个issue再来bb。您在这试图抹黑我也就算了，把您所推崇的本项目作者也一并抹黑，真的是传说中的 “我疯起来连我自己都喷” 啊

**Comment by seqilove** [comment]
问题来了，就因为你想卖你所谓的后端 这个作者影响你了？他也没像你一样收费啊。
为了自己伟光正，你也真的用心良苦了，亡羊补牢似的给这个作者发几条issue，你这才真的洗的一手好地。。。佩服佩服 要是github能改issues的发布时间，估计你就真的洗地成功了呢！

**Comment by Zzm317** [comment]
@seqilove 至于你所说的 whmcs-shadowsocks-plugin 的代码涉及是别人的收费项目，请去找 @kesuki 别来泼我污水。https://github.com/kesuki/whmcs-shadowsocks-plugin/tree/8cf138baf536c0a814312ef442f35744ec19f581 这个项目init的时候就什么都没说那不是我的锅，别把这帽子往我头上扣。再顺便，如果 whmcs-shadowsocks-plugin 涉及抄袭，那么本项目不仅应该说明二开自 whmcs-shadowsocks-plugin 还应该说明 whmcs-shadowsocks-plugin 原插件的原作者。这在本质上没有任何区别，也是您所谓的 “项目说明里面完全没有提到你抄袭的对象呢”

**Comment by Zzm317** [comment]
@seqilove 至于您所说的 “就因为你想卖你所谓的后端” 我可没说想卖，在https://github.com/Zzm317/V2raySocks 中没有任何地方提到需要购买我的后端，只有人家提issue问的时候我才回复了。你这黑的真的一点道理都没有啊。我洗地？我洗什么地？我全程的锅只有一个没有及时回复原作者的回复而已。您这洗地技术还得再练练

**Comment by Zzm317** [comment]
@seqilove 至于后端开发，很简单，数据库文件都是开源的，你想开发直接自己开发，没必要买我写的版本，至于“亡羊补牢似的给这个作者发几条issue”？ 我对技术层面的东西向来毫无保留，我甚至可以完整告诉你我的manager的业务逻辑，也可以告诉你我import了哪些库，如果你觉得我是 “为了自己伟光正” 那简单，你呢先去提issue让删掉 whmcs-shadowsocks-plugin 和所有的二开，然后再给这作者写一个插件，然后持续维护即可。最好再给这作者写一套完整的后端开发流程，来证明你的英勇伟大正义呗。

**Comment by seqilove** [comment]
你这人可真是“宽以待己 严于律人”，既然你都承认抄袭神奇海螺的whmcs-shadowsocks-plugin 插件了，你为什么还能厚着脸皮在这说呢？而且你自己可能都没发现你有一个很大的逻辑漏洞，既然你的UnlimitedSocks是fork的https://github.com/kesuki/whmcs-shadowsocks-plugin，那么为什么在README.MD没有说明呢？而且https://github.com/kesuki/whmcs-shadowsocks-plugin项目留的都是你的信息，是不是可以认为本身就是你的小号？

**Comment by Zzm317** [comment]
@seqilove 至于你所说的时间问题，“包括为什么我这几天都没有回，因为我在进行严格的代码检查，来判断是不是有这个必要去删除或怎么样。” 了解一下

**Comment by Zzm317** [comment]
@seqilove “既然你的UnlimitedSocks是fork的https://github.com/kesuki/whmcs-shadowsocks-plugin，那么为什么在README.MD没有说明呢？而且https://github.com/kesuki/whmcs-shadowsocks-plugin项目留的都是你的信息，是不是可以认为本身就是你的小号？” 自己看看https://github.com/kesuki/whmcs-shadowsocks-plugin/graphs/contributors 我是接盘开发者，不留我的信息留你的？你去修bug？

**Comment by Zzm317** [comment]
@seqilove 您可别扯了吧，ssr最开始可是只发布了二进制文件的。至于“改的UnlimitedSocks为什么没提到来源于kesuki的项目？” 您可睁大眼睛看看清楚，我那是fork的项目不是新项目，你直接github搜是搜不到的大兄弟 https://github.com/search?q=unlimitedsocks 自己看

**Comment by Zzm317** [comment]
@seqilove 看看清楚啊
Zzm317/Unlimited-Socks
forked from kesuki/whmcs-shadowsocks-plugin
forked from forked from forked from
重要的事情说三遍

**Comment by Zzm317** [comment]
如果这个作者也是 forked from 那我连这个issue都不会提，就是因为不是forked from所以才有了后面这一堆事了解一下
