### ISSUE TITLE
server运行bug

### ISSUE THREAD

**Issue by mayday12138** [Npist/v2rayMS#10]
用screen后台运行后，有时候服务挂了，进去看server一直输出(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')
(0, '')

**Comment by mayday12138** [comment]
这是client端的error
Traceback (most recent call last):
  File "v2rayMS_Client.py", line 314, in <module>
    main()
  File "v2rayMS_Client.py", line 297, in main
    accept_cfg()
  File "v2rayMS_Client.py", line 256, in accept_cfg
    user_config_temp = accept_data(Gud_str)
  File "v2rayMS_Client.py", line 230, in accept_data
    sock.sendall(b'!#%')
BrokenPipeError: [Errno 32] Broken pipe

**Comment by mlgexyz** [comment]
我这边也遇到了，情况一模一样，不过你这边server输出不完全，最顶行还有一句
> 2013 - Lost connection to MySQL server during query
应该是长时间开着然后数据库链接出错了？

**Comment by mayday12138** [comment]
有没有可能是后台运行的时候，在前台有运行了一些程序导致了v2rayms的崩溃

**Comment by Npist** [comment]
因为各种原因导致的mysql连接中断 已修复  添加了错误重连  获取最近版本即可

**Comment by Npist** [comment]
如果还有问题联系 https://t.me/npist
