### ISSUE TITLE
数据库连接报错

### ISSUE THREAD

**Issue by HavenLiu** [Npist/v2rayMS#13]
运行python3 v2rayMS_Server.py
报数据库连接错误，测试数据库是可以正常连接的，远程连接也没问题
[Queue]:Wed Oct 17 17:38:30 2018:Mysql Connection Error
[Queue]:Wed Oct 17 17:38:40 2018:Mysql Connection Error
[Queue]:Wed Oct 17 17:38:50 2018:Mysql Connection Error
^CException ignored in: <module 'threading' from '/usr/lib64/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 1285, in _shutdown
    t.join()
  File "/usr/lib64/python3.4/threading.py", line 1051, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.4/threading.py", line 1067, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

**Comment by Npist** [comment]
1.确认sqlconn.json是否在当前工作目录下
2.升级python版本至3.6

**Comment by HavenLiu** [comment]
1、sqlconn.json文件和v2rayMS_Server.py在同一目录
2、之前python确实是3.4的版本，现在已经升级到3.6，问题依然

**Comment by Npist** [comment]
连带你执行的命令给我看一下  同一目录不等于工作目录  还不行的话联系https://t.me/npist我给你看看

**Comment by Npist** [comment]
https://t.me/npist

**Comment by 755048652** [comment]
同上面的问题，数据库链接错误。你给的https://t.me/npist好像是订阅号

**Comment by Npist** [comment]
你们不会用telegram群？？？？？？

**Comment by Npist** [comment]
确认你们数据库连接信息正确  且是否安装有python的pymysql模块，如果均没有发现问题，邮箱联系我npist35@gamil.com
