### ISSUE TITLE
dalao有搭建教程么，我试了好几次都失败了。谢谢大佬

### ISSUE THREAD

**Issue by Helpayment** [Npist/v2rayMS#15]
dalao有搭建教程么，我试了好几次都失败了。谢谢大佬

**Comment by Npist** [comment]
安装方法在readme中已经介绍的很详细了，有疑难请提供环境、报错、截图等相关信息

**Comment by victoryLV** [comment]
教程里图片加载不出来，大佬有在宝塔搭建的方法吗，谢谢

**Comment by victoryLV** [comment]
dalao这里有个教程，您看看怎么能和您的整合一下，感谢大佬。https://44i.im/2018/09/19/whmcs%E5%AE%89%E8%A3%85%E6%8F%92%E4%BB%B6%E9%94%80%E5%94%AEV2Ray/

**Comment by Npist** [comment]
可参考性不高  
仔细阅读项目readme中的说明
whmcs模块安装可以参考http://www.mak-blog.com/whmcs-shadowsocks-plugin.html
后端安装详细参考readme中的使用部分

**Comment by victoryLV** [comment]
您好，我搭建后端到这一步不会了，Server目录存放进数据库服务器
，我写了个宝塔搭建教程，您有时间可以改改么，谢谢您。
https://shimo.im/docs/uzXxvYwfpr4we7Xd/ 「v2rayMS forWHMCS」，可复制链接后用石墨文档 App 打开

**Comment by Npist** [comment]
python运行环境有问题  没有正确安装
python -V确认使用的python版本
pip -V确认pip的python版本
确保是在python3.6下

**Comment by victoryLV** [comment]
老哥，我安装好python3.6和pymysql模块之后，在client]目录运行 python3 v2rayMS_Client.py和server/目录下运行python3 v2rayMS_Server.py出现以下报错
![ohn2sr_w8b35 y3_id c t](https://user-images.githubusercontent.com/32597550/47839860-40453600-ddef-11e8-8e56-061e140cbd54.png)
![zobktg_ l gtc1bul7 7m7](https://user-images.githubusercontent.com/32597550/47839864-42a79000-ddef-11e8-9ba3-5d6c694fd732.png)
