### ISSUE TITLE
几个小小的建议

### ISSUE THREAD

**Issue by Zzm317** [Npist/v2rayMS#2]
在数据表增加email字段不太明智，建议和我一样直接使用id然后组合特点的邮件后缀来实现用户区分。（就好像1@loli.ren这样
还有就是建议把插件单独做成项目。这样更利于版本更新和维护。目前你我的分支的sql部分只有email字段的区别。所以其实你可以参考一下上面的建议把更多的时间放在研究后端编写上
然后就是没记错的话目前python似乎有现成的grpc对接v2ray的项目，你可以参考一下来做流量调取和上传

**Comment by Npist** [comment]
是的  后面会修改为由其他用户特定字符段实现流量统计    开始这个项目很大部分原因只是为了学习Python过程中的练习  所以并没有进行过多的调查  代码中也有很多没有考虑周到且有很多无用代码的情况   感谢建议

如果后面这个项目考虑长期维护的话，会建议用户使用您的v2raysocks项目并进行源码的修改

**Comment by Zzm317** [comment]
开电脑看了下
https://github.com/ThunderingII/v2ray_python_client
这个是项目，然后就是我不会python所以就没法一起开发了=-=
我是直接用go实现的后端，毕竟出售所以就不能开源，不过出售了不代表我不能开发别的开源项目啊hhhhh
拉流量主要就还是一个api然后上传。
然后提个建议，不要使用/etc下面的v2ray.json，直接/usr/bin/v2ray/v2ray -config来运行，这样文件的分布会舒服很多，而且方便部署新功能。

**Comment by Zzm317** [comment]
然后增删用户也最好直接用api实现，这样可以避免大量用户增删的时候造成用户体验下降，就还是上面说到的那个python项目，用grpc实现。

**Comment by Zzm317** [comment]
"inboundDetour": [{
    "listen": "0.0.0.0",
    "port": 8301,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "0.0.0.0"
    },
    "tag": "api"
  }],
大概就是这样的inboundDetour就可以了。需要完整的json的话你和我说我直接发你邮箱。
