### ISSUE TITLE
已经上传插件到servers文件夹，但是whmcs后台没有显示插件信息

### ISSUE THREAD

**Issue by miniaoe** [Npist/v2rayMS#3]
![image](https://user-images.githubusercontent.com/21149432/45464944-777b5d00-b745-11e8-8083-0b79b39e9be5.png)
![image](https://user-images.githubusercontent.com/21149432/45464960-88c46980-b745-11e8-88ed-da2915d7b816.png)

但是后台并没有显示v2RayMs信息，请问这个改如何处理

**Comment by Npist** [comment]
修改下文件名   V2rayMS.php 改成 v2rayMS.php  上传github时忘记了

Dilili <notifications@github.com> 于2018年9月13日周四 上午11:10写道：

**Comment by miniaoe** [comment]
感谢

**Comment by victoryLV** [comment]
> 感谢

大佬，后端您会安装吗
