### ISSUE TITLE
后端程序报错

### ISSUE THREAD

**Issue by mayday12138** [Npist/v2rayMS#4]
root@ip-172-31-45-239:/www/wwwroot/v2rayMS-master/client# python3 v2rayMS_Client.py
Linux
Sat Sep 15 17:42:47 2018
data receive done .... 0
Update user list
Traceback (most recent call last):
  File "v2rayMS_Client.py", line 310, in <module>
    main()
  File "v2rayMS_Client.py", line 293, in main
    accept_cfg()
  File "v2rayMS_Client.py", line 260, in accept_cfg
    user_config_list = [eval(i) for i in user_config_temp.split("#")]
  File "v2rayMS_Client.py", line 260, in <listcomp>
    user_config_list = [eval(i) for i in user_config_temp.split("#")]
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing

**Comment by Npist** [comment]
我也发现了这样的问题  socket通讯中有时可能会因为网络问题造成的接受到空数据包  因为客户端程序没有做校验 所以会出现这样的报错  只需要让程序忽略过空数据包就行   最近会提交修改   但我发现的只是偶发性的  如果你是在某些情况下确定会出现  麻烦吧具体的细节情况邮件告知我（包括节点及服务器的位置、延迟、最好可以提供ip等信息）

**Comment by mayday12138** [comment]
可能是我配置有问题吧，whmcs和services运行在一个服务器上，services运行没报错，监听正常，后端应该是我配置问题，服务器ip填services端ip，域名改主站域名，其他不变对吧

**Comment by Npist** [comment]
同一服务器上填127.0.0.1就可以了  域名填什么域名都可以  只是用来生成邮箱进行流量统计的

**Comment by Npist** [comment]
已经成功了   如果连接不上检查防火墙及v2ray配置

**Comment by mayday12138** [comment]
需要自己修改Client的config吗，我直接用的默认的

**Comment by Npist** [comment]
参考官方文件配置即可  程序只更新client字段
