### ISSUE TITLE
后端无法正常开启

### ISSUE THREAD

**Issue by mlgexyz** [Npist/v2rayMS#5]
![default](https://user-images.githubusercontent.com/21287731/45770844-1dfbbc80-bc76-11e8-8f2f-c2b0978cc954.png)

**Comment by Npist** [comment]
数据库连接失败  检查数据库信息是否配置正确

**Comment by mlgexyz** [comment]
谢谢提醒，全局查找了一下sqlconn.json文件，发现程序调用的是root目录下的哪一个，而非程序目录下的那个，手动改了源码解决了

**Comment by Npist** [comment]
因为你是在根目录下运行的   程序默认读取的是当前工作目录下的配置文件  之后会修改一下这块
