### ISSUE TITLE
config里的client列表一直是空的

### ISSUE THREAD

**Issue by mlgexyz** [Npist/v2rayMS#6]
client一直是输出用户列表更新成功的。。。可以检测到数据库里用户列表变动，但v2ray的配置文件里面就一直是空的

**Comment by Npist** [comment]
确认一下数据库是否有数据   我提供的配置文件只是进行流量统计的参考配置  默认使用的还是v2ray默认位置的 /etc/v2ray/config.json

**Comment by mlgexyz** [comment]
数据库有数据，路径也是对的:confused:

**Comment by Npist** [comment]
加下https://t.me/npist   我一会给你看看

**Comment by mlgexyz** [comment]
@Npist 九点半放学，现在在学校，放学了有电脑把v2ray开回来再加你

**Comment by mlgexyz** [comment]
频道已加

**Comment by mlgexyz** [comment]
经过作者查明是py版本问题，已解决，Tks
