### ISSUE TITLE
关于v2ray配置文件的位置

### ISSUE THREAD

**Issue by mayday12138** [Npist/v2rayMS#7]
看了后端源码，发现定义config文件是etc/v2ray/config.json,所以说连接时配置服务器是按照etc/v2ray里的配置而不是后端同目录下的config配置是不是，望解答

**Comment by Npist** [comment]
同目录下只是我提供的一个支持流量统计的模版，实际使用是默认位置，你可以自己修改，仅需要修改在源代码头部定义的全局变量即可

**Comment by mayday12138** [comment]
ok已经搞定了，问问大佬用的什么主题感觉好好看

**Comment by mayday12138** [comment]
pull request看一下

**Comment by mayday12138** [comment]
没找到生成链接的代码，想修复二维码和链接没有服务器名称的bug

**Comment by victoryLV** [comment]
大佬，您在搭建的时候能写个教程或录个视频么，谢谢大佬
